### ISSUE TITLE
Can't integrate with emm and appm

### ISSUE THREAD

**Issue by yuxian0311** [wso2/product-app-manager#329]
I'm trying to integrate with emm and appm. I followed the document [https://docs.wso2.com/display/APPM110/Integrating+a+Mobile+Device+Manager]. And I have installed the wso2 agent for android, when I click install at mobile app store,  it says 'Sorry you dont have devices to install this app'.
Can anyone help me? I'll be very appreciate your help!

**Comment by sagara-gunathunga** [comment]
This repository is in maintains mode and there is no releases planed.
