### ISSUE TITLE
Fail to add custom SSOConfigurator implementations

### ISSUE THREAD

**Issue by dinusha-dilrukshi** [wso2/product-app-manager#359]
**Description:**
Default SSOConfigurator class provided in App Manager can be extended or override by implementing org.wso2.carbon.appmgt.impl.idp.sso.configurator.SSOConfigurator interface and putting new implementation as an OSGi bundle to droppins. Then changing following config in app-manager.xml by putting new implementation.

<providerClass>org.wso2.carbon.appmgt.impl.idp.sso.configurator.IS500SAMLSSOConfigurator</providerClass>

But doing this fails in AppM-1.2.0, due to OSGi class loading issue. 

**Suggested Labels:**
Type/Bug

**Suggested Assignees:**
dinusha-dilrukshi

**Affected Product Version:**
1.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by madurangasiriwardena** [comment]
Closing the issues since the repo is no longer actively maintained.
